/* tslint:disable */
/* eslint-disable */
/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: 2021.3.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Script primitive for which at least a given number of signing keys corresponding to the list elements' verification keys are expected to make the script valid.
 * @export
 * @interface ApiScriptSome
 */
export interface ApiScriptSome {
    /**
     * 
     * @type {number}
     * @memberof ApiScriptSome
     */
    at_least: any;
    /**
     * 
     * @type {Array&lt;ScriptValue&gt;}
     * @memberof ApiScriptSome
     */
    from: any;
}
