/* tslint:disable */
/* eslint-disable */
/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: 2021.3.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ApiNetworkInformation
 */
export interface ApiNetworkInformation {
    /**
     * 
     * @type {ApiNetworkInformationSyncProgress}
     * @memberof ApiNetworkInformation
     */
    sync_progress: any;
    /**
     * 
     * @type {ApiNetworkInformationNodeTip}
     * @memberof ApiNetworkInformation
     */
    node_tip: any;
    /**
     * 
     * @type {ApiNetworkInformationNetworkTip}
     * @memberof ApiNetworkInformation
     */
    network_tip?: any;
    /**
     * 
     * @type {WalletsDelegationChangesAt}
     * @memberof ApiNetworkInformation
     */
    next_epoch?: any;
    /**
     * 
     * @type {string}
     * @memberof ApiNetworkInformation
     */
    node_era: ApiNetworkInformationNodeEraEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum ApiNetworkInformationNodeEraEnum {
    Byron = 'byron',
    Shelley = 'shelley',
    Allegra = 'allegra',
    Mary = 'mary'
}

