/* tslint:disable */
/* eslint-disable */
/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: 2021.3.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { StakepoolsCost, StakepoolsMargin, StakepoolsMetadata, StakepoolsMetrics, StakepoolsPledge, StakepoolsRetirement } from ".";

/**
 * 
 * @export
 * @interface ApiStakePool
 */
export interface ApiStakePool {
    /**
     * A unique identifier for the pool.
     * @type {string}
     * @memberof ApiStakePool
     */
    id: any;
    /**
     * 
     * @type {StakepoolsMetrics}
     * @memberof ApiStakePool
     */
    metrics: StakepoolsMetrics;
    /**
     * 
     * @type {StakepoolsCost}
     * @memberof ApiStakePool
     */
    cost: StakepoolsCost;
    /**
     * 
     * @type {StakepoolsMargin}
     * @memberof ApiStakePool
     */
    margin: StakepoolsMargin;
    /**
     * 
     * @type {StakepoolsPledge}
     * @memberof ApiStakePool
     */
    pledge: StakepoolsPledge;
    /**
     * 
     * @type {StakepoolsMetadata}
     * @memberof ApiStakePool
     */
    metadata?: StakepoolsMetadata;
    /**
     * 
     * @type {StakepoolsRetirement}
     * @memberof ApiStakePool
     */
    retirement?: StakepoolsRetirement;
    /**
     * Various flags applicable to stake pools. Possible flags:  | flag     | description                                                                                                      | | ---      | ---                                                                                                              | | delisted | The pool is marked as delisted on a configured SMASH server; metadata for this pool have therefore been dropped. | 
     * @type {Array&lt;string&gt;}
     * @memberof ApiStakePool
     */
    flags: Array<ApiStakePoolFlagsEnum>;
}

/**
    * @export
    * @enum {string}
    */
export enum ApiStakePoolFlagsEnum {
    Delisted = 'delisted'
}

