/* tslint:disable */
/* eslint-disable */
/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: 2021.3.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse20013
 */
export interface InlineResponse20013 {
    /**
     * The hash of genesis block
     * @type {string}
     * @memberof InlineResponse20013
     */
    genesis_block_hash: any;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20013
     */
    blockchain_start_time: any;
    /**
     * 
     * @type {ApiNetworkParametersSlotLength}
     * @memberof InlineResponse20013
     */
    slot_length: any;
    /**
     * 
     * @type {ApiNetworkParametersEpochLength}
     * @memberof InlineResponse20013
     */
    epoch_length: any;
    /**
     * 
     * @type {WalletsTipHeight}
     * @memberof InlineResponse20013
     */
    security_parameter: any;
    /**
     * 
     * @type {ApiNetworkParametersActiveSlotCoefficient}
     * @memberof InlineResponse20013
     */
    active_slot_coefficient: any;
    /**
     * 
     * @type {ApiNetworkParametersActiveSlotCoefficient}
     * @memberof InlineResponse20013
     */
    decentralization_level: any;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20013
     */
    desired_pool_number: any;
    /**
     * 
     * @type {WalletswalletIdpaymentfeesAmount}
     * @memberof InlineResponse20013
     */
    minimum_utxo_value: any;
    /**
     * 
     * @type {ApiNetworkParametersEras}
     * @memberof InlineResponse20013
     */
    eras: any;
}
