/* tslint:disable */
/* eslint-disable */
/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: 2021.3.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse415
 */
export interface InlineResponse415 {
    /**
     * A descriptive error message.
     * @type {string}
     * @memberof InlineResponse415
     */
    message: any;
    /**
     * A specific error code for this error, more precise than HTTP ones.
     * @type {string}
     * @memberof InlineResponse415
     */
    code: any;
}
