/* tslint:disable */
/* eslint-disable */
/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: 2021.3.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse2006
 */
export interface InlineResponse2006 {
    /**
     * A unique identifier for the pool.
     * @type {string}
     * @memberof InlineResponse2006
     */
    id: any;
    /**
     * 
     * @type {StakepoolsMetrics}
     * @memberof InlineResponse2006
     */
    metrics: any;
    /**
     * 
     * @type {StakepoolsCost}
     * @memberof InlineResponse2006
     */
    cost: any;
    /**
     * 
     * @type {StakepoolsMargin}
     * @memberof InlineResponse2006
     */
    margin: any;
    /**
     * 
     * @type {StakepoolsPledge}
     * @memberof InlineResponse2006
     */
    pledge: any;
    /**
     * 
     * @type {StakepoolsMetadata}
     * @memberof InlineResponse2006
     */
    metadata?: any;
    /**
     * 
     * @type {StakepoolsRetirement}
     * @memberof InlineResponse2006
     */
    retirement?: any;
    /**
     * Various flags applicable to stake pools. Possible flags:  | flag     | description                                                                                                      | | ---      | ---                                                                                                              | | delisted | The pool is marked as delisted on a configured SMASH server; metadata for this pool have therefore been dropped. | 
     * @type {Array&lt;string&gt;}
     * @memberof InlineResponse2006
     */
    flags: Array<InlineResponse2006FlagsEnum>;
}

/**
    * @export
    * @enum {string}
    */
export enum InlineResponse2006FlagsEnum {
    Delisted = 'delisted'
}

