/* tslint:disable */
/* eslint-disable */
/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: 2021.3.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Defines a larger unit for the asset, in the same way Ada is the larger unit of Lovelace. 
 * @export
 * @interface NativeAssetsMetadataUnit
 */
export interface NativeAssetsMetadataUnit {
    /**
     * The number of digits after the decimal point. 
     * @type {number}
     * @memberof NativeAssetsMetadataUnit
     */
    decimals: any;
    /**
     * The human-readable name for the larger unit of the asset. Used for display in user interfaces. 
     * @type {string}
     * @memberof NativeAssetsMetadataUnit
     */
    name: any;
}
