/* tslint:disable */
/* eslint-disable */
/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: 2021.3.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface NothingToMigrate
 */
export interface NothingToMigrate {
    /**
     * May occur when trying to migrate a wallet that is empty or full of dust.
     * @type {string}
     * @memberof NothingToMigrate
     */
    message: any;
    /**
     * 
     * @type {string}
     * @memberof NothingToMigrate
     */
    code: NothingToMigrateCodeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum NothingToMigrateCodeEnum {
    Migrate = 'nothing_to_migrate'
}

