/* tslint:disable */
/* eslint-disable */
/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: 2021.3.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * The rewards the wallet can expect to receive at the end of an epoch, in the long term, if delegating to this pool.  For more details, see the [Design Specification for Delegation and Incentives in Cardano](https://hydra.iohk.io/job/Cardano/cardano-ledger-specs/delegationDesignSpec/latest/download-by-type/doc-pdf/delegation_design_spec) document. 
 * @export
 * @interface StakepoolsMetricsNonMyopicMemberRewards
 */
export interface StakepoolsMetricsNonMyopicMemberRewards {
    /**
     * 
     * @type {number}
     * @memberof StakepoolsMetricsNonMyopicMemberRewards
     */
    quantity: any;
    /**
     * 
     * @type {string}
     * @memberof StakepoolsMetricsNonMyopicMemberRewards
     */
    unit: StakepoolsMetricsNonMyopicMemberRewardsUnitEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum StakepoolsMetricsNonMyopicMemberRewardsUnitEnum {
    Lovelace = 'lovelace'
}

