/* tslint:disable */
/* eslint-disable */
/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: 2021.3.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { StakepoolsMetricsNonMyopicMemberRewards } from ".";

/**
 * 
 * @export
 * @interface StakepoolsMetrics
 */
export interface StakepoolsMetrics {
    /**
     * 
     * @type {StakepoolsMetricsNonMyopicMemberRewards}
     * @memberof StakepoolsMetrics
     */
    non_myopic_member_rewards: StakepoolsMetricsNonMyopicMemberRewards;
    /**
     * 
     * @type {StakepoolsMetricsRelativeStake}
     * @memberof StakepoolsMetrics
     */
    relative_stake: any;
    /**
     * Saturation-level of the pool based on the desired number of pools aimed by the network. A value above `1` indicates that the pool is saturated.  The `non_myopic_member_rewards` take oversaturation into account, as specified by the [specs](https://hydra.iohk.io/job/Cardano/cardano-ledger-specs/delegationDesignSpec/latest/download-by-type/doc-pdf/delegation_design_spec).  The saturation is based on the live `relative_stake`. The saturation at the end of epoch e, will affect the rewards paid out at the end of epoch e+3. 
     * @type {number}
     * @memberof StakepoolsMetrics
     */
    saturation: any;
    /**
     * 
     * @type {StakepoolsMetricsProducedBlocks}
     * @memberof StakepoolsMetrics
     */
    produced_blocks: any;
}
