/* tslint:disable */
/* eslint-disable */
/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: 2021.3.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Information about the stake pool. 
 * @export
 * @interface StakepoolsMetadata
 */
export interface StakepoolsMetadata {
    /**
     * 
     * @type {string}
     * @memberof StakepoolsMetadata
     */
    ticker: any;
    /**
     * 
     * @type {string}
     * @memberof StakepoolsMetadata
     */
    name: any;
    /**
     * 
     * @type {string}
     * @memberof StakepoolsMetadata
     */
    description?: any;
    /**
     * 
     * @type {string}
     * @memberof StakepoolsMetadata
     */
    homepage: any;
}
