/* tslint:disable */
/* eslint-disable */
/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: 2021.3.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TransactionAlreadyInLedger
 */
export interface TransactionAlreadyInLedger {
    /**
     * Occurs when attempting to delete a transaction which is neither pending nor expired.
     * @type {string}
     * @memberof TransactionAlreadyInLedger
     */
    message: any;
    /**
     * 
     * @type {string}
     * @memberof TransactionAlreadyInLedger
     */
    code: TransactionAlreadyInLedgerCodeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum TransactionAlreadyInLedgerCodeEnum {
    Ledger = 'transaction_already_in_ledger'
}

