/* tslint:disable */
/* eslint-disable */
/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: 2021.3.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UnsupportedMediaType
 */
export interface UnsupportedMediaType {
    /**
     * May occur when providing an invalid 'Content-Type' header.
     * @type {string}
     * @memberof UnsupportedMediaType
     */
    message: any;
    /**
     * 
     * @type {string}
     * @memberof UnsupportedMediaType
     */
    code: UnsupportedMediaTypeCodeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum UnsupportedMediaTypeCodeEnum {
    Type = 'unsupported_media_type'
}

