/* tslint:disable */
/* eslint-disable */
/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: 2021.3.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { WalletsAssetsAvailable } from ".";

/**
 * Current non-Ada asset holdings of the wallet.  The amount of assets available to spend may be less than the total unspent assets due to transaction change amounts which are yet to be fully confirmed (pending). 
 * @export
 * @interface WalletsAssets
 */
export interface WalletsAssets {
    /**
     * Available UTxO asset balances (funds that can be spent without condition). 
     * @type {Array&lt;WalletsAssetsAvailable&gt;}
     * @memberof WalletsAssets
     */
    available: Array<WalletsAssetsAvailable>;
    /**
     * Total asset balances (available balances plus pending change balances). 
     * @type {Array&lt;WalletsAssetsAvailable&gt;}
     * @memberof WalletsAssets
     */
    total: Array<WalletsAssetsAvailable>;
}
