/* tslint:disable */
/* eslint-disable */
/**
 * Cardano Wallet Backend API
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p> 
 *
 * OpenAPI spec version: 2021.3.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * The Ada balance of the reward account for this wallet.
 * @export
 * @interface WalletsBalanceReward
 */
export interface WalletsBalanceReward {
    /**
     * 
     * @type {number}
     * @memberof WalletsBalanceReward
     */
    quantity: number;
    /**
     * 
     * @type {string}
     * @memberof WalletsBalanceReward
     */
    unit: WalletsBalanceRewardUnitEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum WalletsBalanceRewardUnitEnum {
    Lovelace = 'lovelace'
}

